<?php

namespace ContainerBpJGDSj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessDeniedListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\AccessDeniedListener' shared autowired service.
     *
     * @return \App\EventListener\AccessDeniedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/AccessDeniedListener.php';

        return $container->privates['App\\EventListener\\AccessDeniedListener'] = new \App\EventListener\AccessDeniedListener(($container->services['router'] ?? self::getRouterService($container)), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
