<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBpJGDSj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBpJGDSj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBpJGDSj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBpJGDSj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBpJGDSj\App_KernelDevDebugContainer([
    'container.build_hash' => 'BpJGDSj',
    'container.build_id' => '86cdedbd',
    'container.build_time' => 1746452756,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBpJGDSj');
