<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU4h4zOG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU4h4zOG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU4h4zOG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU4h4zOG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU4h4zOG\App_KernelDevDebugContainer([
    'container.build_hash' => 'U4h4zOG',
    'container.build_id' => 'c4ecc7e6',
    'container.build_time' => 1743157655,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU4h4zOG');
